server:
  port: 8080
spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/account
    username: "root"
    password: "ayush@123"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


