server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/account
    username: "root"
    password: "ayush@123"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs






